# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labelers

name: Labeler
on:
  pull_request:
    branches:
       - Release1.1
       - main
       - PR_test
env:
  PR_NUMBER: ${{ github.event.pull_request.number }}
  Label_Name: LargePR
  Set_Comments: This comment will apply when they're more than ten commits



jobs:
  label:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
        - name: Hello world action step
          id: commit
          uses: PunithMohan/custom-workflow-test@v1.13
          with:
             commit-count: '5'
        - name: Get the commit count for PR
          run: |
           echo "Commits_count=$(curl \
           -X GET \
           -H "Accept: application/vnd.github.v3+json" \
           -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
           https://api.github.com/repos/${{ github.repository }}/pulls/${{ env.PR_NUMBER }}/commits | grep parents | wc -l)" >> $GITHUB_ENV               
        - name: Create and apply label to PR
          run: |
            echo "Commits_count:  ${{ env.Commits_count }}"
            echo "commit from custom template : ${{ steps.commit.outputs.CommitsCounts }}"
            if [[ "${{ env.Commits_count }}" -ge "${{ steps.commit.outputs.CommitsCounts }}" ]]; then
            
            echo "Create label"
            curl \
            -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/labels \
            -d '{"name":"LargePR","color":"1d76db"}'  
            
             echo "Apply label to PR"            
             curl \
             -X POST \
             -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}/issues/${{ env.PR_NUMBER }}/labels \
              -d '{"labels":["LargePR"]}' 
              
            echo "Applying comments after label"            
             curl \
             -X POST \
             -H "Accept: application/vnd.github.v3+json" \
             -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              https://api.github.com/repos/${{ github.repository }}/issues/${{ env.PR_NUMBER }}/comments \
              -d '{"body":"The PR should have less than 10 commits"}'
   
            fi
           
          
